### ISSUE TITLE
The response has no "Link" HTTP header

### ISSUE THREAD

**Issue by karser** [api-platform/api-doc-parser#10]
I'm using api-platform 2.1beta1 and I have completed all [admin instruction steps](https://github.com/api-platform/admin).
I'm getting an error:
```
parseHydraDocumentation.js:71 Uncaught (in promise) Error: The response has no "Link" HTTP header.
    at getDocumentationUrlFromHeaders (parseHydraDocumentation.js:71)
    at parseHydraDocumentation.js:95
    at <anonymous>
```
because getDocumentationUrlFromHeaders needs Link header, but at [this line](https://github.com/dunglas/api-doc-parser/blob/master/src/hydra/parseHydraDocumentation.js#L63) headers are empty
![image](https://user-images.githubusercontent.com/1675033/27076838-f4a6fa0e-5036-11e7-9a37-dde3fc0826cd.png)

Although it's not true, see the response headers:
![image](https://user-images.githubusercontent.com/1675033/27076916-30af843a-5037-11e7-9349-e739bba3135e.png)
and response body, for the reference:
![image](https://user-images.githubusercontent.com/1675033/27076998-69e74670-5037-11e7-801e-3cb00b0f077e.png)

**Comment by Gounlaf** [comment]
Hi @karser,

Take a look at this issue: https://github.com/api-platform/admin/issues/9

**Comment by mysiar** [comment]
for nelmio cors  : 
```
            expose_headers: ["Link"]
```
