### ISSUE TITLE
[DataProvider] Empty Headers and 401 response

### ISSUE THREAD

**Issue by RSalo** [api-platform/api-doc-parser#100]
**API Platform version(s) affected**: 2.6.4

**Description**  
I try to add JWT token to the header, but it stays empty no matter what returning 401 response.

**How to reproduce**  
```JS
function App() {

    const getHeaders = () => localStorage.getItem("token") ? {
        Authorization: `Bearer ${localStorage.getItem("token")}`,
    } : {};

    const customFetchHydra = (url, options = {}) => {
        fetchHydra(url, {
            ...options,
            headers: new Headers(getHeaders()),
        })
    };

    const dataProvider = hydraDataProvider(API_ENTRYPOINT, customFetchHydra);

    return (
        <HydraAdmin ... dataProvide={dataProvider} ...>
            ...
        </HydraAdmin>
    );
}
```

**Possible Solution**  
~

**Additional Context**  
I tried to debug compiled fetchJsonLd.js:
![image](https://user-images.githubusercontent.com/4490762/123244576-bccf3a80-d4ec-11eb-9ec8-82fd5ff82f7a.png)

then I was trying to show all headers in the chrome console at that moment:
![image](https://user-images.githubusercontent.com/4490762/123244967-0fa8f200-d4ed-11eb-96f4-2862077db4b8.png)

I have no idea where "next" comes from...

**Comment by alanpoulain** [comment]
Hello, have you followed https://api-platform.com/docs/admin/authentication-support/?

**Comment by RSalo** [comment]
@alanpoulain Hello. Yes, I did all according to this documentation.

**Comment by alanpoulain** [comment]
It doesn't seem so. For instance:
```js
    const customFetchHydra = (url, options = {}) => {
        fetchHydra(url, {
            ...options,
            headers: new Headers(getHeaders()),
        })
    };
```
Should be:
```js
    const customFetchHydra = (url, options = {}) => {
        fetchHydra(url, {
            ...options,
            headers: getHeaders,
        })
    };
```

**Comment by RSalo** [comment]
@alanpoulain i did it too. Was trying different variants and nothing change...

**Comment by alanpoulain** [comment]
You need to change the `apiDocumentationParser` too:
```js
const apiDocumentationParser = async (entrypoint) => {
    const { api } = await parseHydraDocumentation(entrypoint, { headers: getHeaders });
    return { api };
};
```

**Comment by RSalo** [comment]
@alanpoulain added as third parameter
```JS
    const apiDocumentationParser = async (entrypoint) => {
        try {
            const { api } = await parseHydraDocumentation(entrypoint, { headers: getHeaders });
            return { api };
        } catch (result) {
            if (result.status === 401) {
                // Prevent infinite loop if the token is expired
                localStorage.removeItem("token");

                return {
                    api: result.api,
                    customRoutes: [
                        <Route path="/" />
                    ],
                };
            }

            throw result;
        }
    };
    const dataProvider = hydraDataProvider(API_ENTRYPOINT, customFetchHydra, apiDocumentationParser);
```
And the same situation. I have no idea, it's my fail or bug...

**Comment by RSalo** [comment]
Find out that we have no header options at all:
https://github.com/api-platform/admin/blob/main/src/hydra/dataProvider.js#L245
So "options.headers" is empty and we creating an empty header object 
https://github.com/api-platform/admin/blob/main/src/hydra/fetchHydra.js#L20
As we have clear headers our parser makes a request without any headers
https://github.com/api-platform/admin/blob/main/src/hydra/fetchHydra.js#L28

I can be mistaken...

**Comment by alanpoulain** [comment]
Closing because it was not followed. It seems other users don't have similar issues. Please reopen if it's the case.
