### ISSUE TITLE
Module not found: Can't resolve 'jsonref'

### ISSUE THREAD

**Issue by herndlm** [api-platform/api-doc-parser#120]
**Version(s) affected**: 0.15.7

**Description**  

Trying to upgrade from 0.15.2 to 0.15.7 gives me the following compilation error in our API platform admin app:
```
./node_modules/@api-platform/api-doc-parser/lib/esm/openapi3/handleJson.js
Module not found: Can't resolve 'jsonref' in '/usr/src/admin/node_modules/@api-platform/api-doc-parser/lib/esm/openapi3'
```

I verified that `node_modules/jsonref` exists. I saw that jsonref was recently added and some importing adaptions were done as well. I don't know much about different JS module types and their imports, but could this be one of the ESM/CJS incompatibilities or something like that?

**How to reproduce**  

sorry, leaving this out for now since I'm not sure yet if this is a bug or not.

**Possible Solution**  

**Additional Context**

**Comment by alanpoulain** [comment]
Could you provide a simple reproducer? For instance an application from scratch?

**Comment by alanpoulain** [comment]
Also make sure `jsonref` is updated.

**Comment by alanpoulain** [comment]
I've made the package pure ESM.
Please read https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c.

**Comment by jcubic** [comment]
I'm not able to update `@api-platform/admin` and `@api-platform/api-doc-parser/` updating everything doesn't help. I keep getting error about missing `jsonref`.
