### ISSUE TITLE
First letter of Resource/Entity doesn't appear

### ISSUE THREAD

**Issue by pierre-H** [api-platform/api-doc-parser#17]
Hello,

Because of the function guessNameFromUrl : https://github.com/api-platform/api-doc-parser/blob/3ca336af4974accb54bd72e5e5e20fecad2974f0/src/hydra/parseHydraDocumentation.js#L157
The first letter of every entity/resource in the @api-platform/admin doesn't appear. 

Is it normal ? 

When I change 1 to 0, the admin works as expected in https://github.com/api-platform/api-doc-parser/blob/3ca336af4974accb54bd72e5e5e20fecad2974f0/src/hydra/parseHydraDocumentation.js#L15

I use Api-Platform 2.1

**Comment by mysiar** [comment]
@pierre-H did you use http://host/ or http://host

**Comment by soyuka** [comment]
Might be because of https://github.com/api-platform/core/pull/1296 ?

**Comment by mysiar** [comment]
looks like this is similar problem to https://github.com/api-platform/client-generator/issues/11
both with trailing slash

**Comment by dunglas** [comment]
Good catch @mysiar! We should normalize the URL to prevent such problems.

**Comment by mysiar** [comment]
@dunglas I made Phd on parsing documentation at work today :)

**Comment by mysiar** [comment]
solved at https://github.com/api-platform/api-doc-parser/pull/18
