### ISSUE TITLE
Support on server side?

### ISSUE THREAD

**Issue by leesiongchan** [api-platform/api-doc-parser#20]

**Comment by dunglas** [comment]
We use it server-side (ex: https://github.com/api-platform/client-generator) without problem. Or do you mean something else?

**Comment by leesiongchan** [comment]
Oh sorry, because I see https://github.com/api-platform/api-doc-parser/blob/master/src/hydra/fetchJsonLd.js#L12 and https://github.com/api-platform/api-doc-parser/blob/master/src/hydra/fetchJsonLd.js#L23 are relay on the browser `fetch` api, unless we use `isomorphic-fetch` or otherwise the library will not be working on the server. Perhaps the library should include `isomoprhic-fetch` as a dependency?

**Comment by mysiar** [comment]
@leesiongchan check this tool out dependencies
https://github.com/api-platform/api-platform-doc-parsing-check/blob/master/package.json

**Comment by leesiongchan** [comment]
Sorry I think I am blind, it does write in the documentation.
