### ISSUE TITLE
Support for Swagger documenation format

### ISSUE THREAD

**Issue by arojunior** [api-platform/api-doc-parser#29]
> API Doc Parser is designed to parse any API documentation format and convert it in the same intermediate representation. For now, only Hydra is supported but if you develop a parser for another format, please open a Pull Request to include it in the library.

I want to work in a parser for swagger documentation to be compatible with [client-generator](https://github.com/api-platform/client-generator)

There is some documentation about the layout of this "intermediate representation"? How it should be?

**Comment by dunglas** [comment]
Great that you'll work on that!
Basically, you need to create a new factory function for Swagger that will hydrate the same output as `parseHydraDocumentation` (https://github.com/api-platform/api-doc-parser/blob/master/src/hydra/parseHydraDocumentation.js).

**Comment by mysiar** [comment]
Hi @arojunior looking forward to it. I was thinking to do it myself but day is to short ;)

**Comment by arojunior** [comment]
Hi guys, just to give you a feedback... I think I'm almost there.

@mysiar my day is too short as well, that's why I'm taking so long.

I'm working on it here: [https://github.com/arojunior/api-doc-parser/tree/swagger-parser](https://github.com/arojunior/api-doc-parser/tree/swagger-parser)

**Comment by mysiar** [comment]
@arojunior can we close this issue now?

**Comment by arojunior** [comment]
Sure!
