### ISSUE TITLE
Swagger support

### ISSUE THREAD

**Issue by arojunior** [api-platform/api-doc-parser#35]
The Swagger parser is already in the project. Can we update the Docs?

**Comment by dunglas** [comment]
Yes please!

**Comment by arojunior** [comment]
@dunglas btw, the version was not updated with the swagger parser. can you do that? I need it to get [this PR](https://github.com/api-platform/client-generator/pull/76) mergeed

**Comment by arojunior** [comment]
@dunglas Can you publish the version with the swagger parser included?

**Comment by dunglas** [comment]
Done!
