### ISSUE TITLE
addParameter in parseHydraDocumentation ignoring options parameter

### ISSUE THREAD

**Issue by Lharz** [api-platform/api-doc-parser#40]
Hi !

I was having issues with fetchResource calls getting 401 responses for every requests ; turned out that it was caused by addParameter (called at the end of parseHydraDocumentation) ignoring my Authorization headers (given in options parameter).

Am I doing this wrong or did I missed something ?

Thanks. :-)

**Comment by dunglas** [comment]
You're probably right, it's a new feature I merged recently. Would you mind providing a patch?

**Comment by Lharz** [comment]
Sure, I didn't made one in case I was just using it wrong. Will make a PR in a few days.

Thanks for the answer. :-)

**Comment by alanpoulain** [comment]
`headers` can now be a function too. Should solve the issue.
