### ISSUE TITLE
Extensive API calls due to filter preparation

### ISSUE THREAD

**Issue by olivermack** [api-platform/api-doc-parser#42]
I came across a rather unexpected change in the `api-doc-parser` which suddenly (I mean, of course after an update ;))  issues dedicate `GET` collection requests in order to determine the filter-parameters... for all the known api resources.

I'm pretty much aware that those filter parameters are only populated in the hydra-specs for the collection endpoint but as far as I can see there seems no option to turn that off. Right now, my client application issues around 100 additional API calls (~50 `OPTIONS` + ~50 `GET`) for the initialization which slows down the ramp up of my app tremendously...

As I can't find that much of information except the PRs in the admin and api-doc-parser components I'd like to know any suggestion to _fail forward_ on that topic. I can imagine an option/flag to activate/deactivate the filter-parameter lookups or an additional hook that allows the subsequent enrichment of particular `Resource` objects whenever needed. I'm fine to work on that and to provide PRs, but I'd like to collect some info first.

This relates to #33

**Comment by FACOLOMBANI** [comment]
Same issue for me, i have a big drop in performance.

**Comment by L-Luciano** [comment]
Any news ?
