### ISSUE TITLE
Add OpenAPI v3 support

### ISSUE THREAD

**Issue by dunglas** [api-platform/api-doc-parser#48]
api-doc-parser already supports (partially, see #37) OpenAPI v2. Now that API Platform Core also supports OpenAPI v3, this library should be able to deal with it it too.

**Comment by jfoliveira** [comment]
There are already stable packages for OpenAPI files parsing and validation, including JSON and YAML support.
I would consider simply consume some of those projects that seem to be popular and mature enough to be relied on, such as:

https://www.npmjs.com/package/oas-validator 
https://www.npmjs.com/package/js-yaml
https://github.com/APIDevTools/json-schema-ref-parser

See usage example from the interesting [openapi-contrib/openapi3-generator](https://github.com/openapi-contrib/openapi3-generator) project:
https://github.com/openapi-contrib/openapi3-generator/blob/master/lib/bundler.js

**Comment by alanpoulain** [comment]
Done here: https://github.com/api-platform/api-doc-parser/pull/59.
