### ISSUE TITLE
Cannot convert undefined or null to object.

### ISSUE THREAD

**Issue by SlvrEagle23** [api-platform/api-doc-parser#76]
Attempting to run API Platform client generation on a very basic API Platform with no particularly complex entities set up, running into this error when attempting to parse with OpenAPI version 3:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /home/node/.npm/_npx/233/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/openapi3/handleJson.js:19:34
    at Array.map (<anonymous>)
    at Object.default_1 [as default] (/home/node/.npm/_npx/233/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/openapi3/handleJson.js:16:27)
    at /home/node/.npm/_npx/233/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/openapi3/parseOpenApi3Documentation.js:12:45
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

the JSON I'm handing it, which is autogenerated by API Platform, is valid and the OpenAPI spec says it's completely fine, except it's missing "description" fields on the properties (though these aren't necessary by my understanding).

Given the relative opacity of this error it's not clear where it's failing to parse my JSON. I've spent several hours spinning my wheels on this with no progress, and I'm starting to feel quite bad about it, so any help would be much appreciated.

**Comment by soyuka** [comment]
Looks like `Object.keys(response.paths)` can't be called, the response doesn't have any paths? 

I'd like to reproduce if you could check what data is given to the `handleJson` file maybe we can have more informations.

**Comment by jfoliveira** [comment]
@soyuka I could reproduce it using the API-Platform demo when specifying `--format openapi3`:

`npx @api-platform/client-generator https://demo.api-platform.com/docs.json src/ --resource Book --format openapi3`

Exception:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/{myuser}/.npm/_npx/10629/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/openapi3/handleJson.js:19:34
    at Array.map (<anonymous>)
    at Object.default_1 [as default] (/Users/{myuser}/.npm/_npx/10629/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/openapi3/handleJson.js:16:27)
    at /Users/{myuser}/.npm/_npx/10629/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/openapi3/parseOpenApi3Documentation.js:12:45
```
I tried but couldn't find a fix though.

**Comment by soyuka** [comment]
Can you check the json response and if it has some paths? Maybe that a proper fix would be to throw a better error?
