### ISSUE TITLE
TypeScript: Cannot find name 'Nullable'

### ISSUE THREAD

**Issue by MarkLyck** [api-platform/api-doc-parser#85]
**API Platform version(s) affected**: 0.10.0

**Description**  
Getting this error when running my Typescript build:

```
ERROR in [at-loader] ./node_modules/@api-platform/api-doc-parser/lib/Field.d.ts:2:39 
    TS2304: Cannot find name 'Nullable'.

ERROR in [at-loader] ./node_modules/@api-platform/api-doc-parser/lib/Operation.d.ts:1:43 
    TS2304: Cannot find name 'Nullable'.

ERROR in [at-loader] ./node_modules/@api-platform/api-doc-parser/lib/Resource.d.ts:4:42 
    TS2304: Cannot find name 'Nullable'.

ERROR in [at-loader] ./node_modules/@api-platform/api-doc-parser/lib/Api.d.ts:2:37 
    TS2304: Cannot find name 'Nullable'.
```

There is a `Nullable` type defined, but completely outside this package as in `/@types/nullable.d.ts`

But it looks like it's attempting to parse these lib files first and there's no imports of this nullable type.

**How to reproduce**  
run typescript using this package.

**Comment by gomcodoctor** [comment]
I am trying to use in angular, getting same error

**Comment by gomcodoctor** [comment]
solution

add 

```
"typeRoots": [
      "./node_modules/@api-platform/api-doc-parser/@types"
    ],
```

in tsconfig file

**Comment by soyuka** [comment]
can you add the dependency to this project? it should fix the issue.

**Comment by olivermack** [comment]
@soyuka what do you mean by that? I'm actually having the same issue at the moment and I'm not able to understand your suggestion :)
