### ISSUE TITLE
Use https instead of http

### ISSUE THREAD

**Issue by cooper8686** [api-platform/api-doc-parser#96]
https://github.com/api-platform/api-doc-parser/blob/9ffab8247ac96b0b22d0b184ac7e3b71f30e9c81/src/hydra/parseHydraDocumentation.ts#L56

why used `http` instead of `https`? 
the browsers throw error when use mixed content

**Comment by dunglas** [comment]
Because it's a namespace, not a dereferenceable URL (similar to XML namespaces). It is defined here, and every characters count: http://www.hydra-cg.com/spec/latest/core/#hydra-at-a-glance
